CREATE SCHEMA IF NOT EXISTS PRUEBAS_REMOTO;

DROP TABLE IF EXISTS PRUEBAS_REMOTO.USUARIOS;

CREATE TABLE PRUEBAS_REMOTO.USUARIOS(
		identificador VARCHAR(36) PRIMARY KEY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		edad INTEGER NOT NULL
	);