CREATE SCHEMA IF NOT EXISTS PRUEBAS_LOCAL;

DROP TABLE IF EXISTS PRUEBAS_LOCAL.USUARIOS;

CREATE TABLE PRUEBAS_LOCAL.USUARIOS(
		identificador VARCHAR(36) PRIMARY KEY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		edad INTEGER NOT NULL
	);
