CREATE SCHEMA IF NOT EXISTS PRUEBAS_GENERIC;

DROP TABLE IF EXISTS PRUEBAS_GENERIC.MATRICULAS;

DROP TABLE IF EXISTS PRUEBAS_GENERIC.MESSAGE_FALLBACK;

CREATE TABLE PRUEBAS_GENERIC.MATRICULAS(
		identificador VARCHAR(36) PRIMARY KEY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		asignatura VARCHAR(100) NOT NULL,
		usuario VARCHAR(100) NOT NULL
	);
	
CREATE TABLE PRUEBAS_GENERIC.MESSAGE_FALLBACK(
	id VARCHAR(36) PRIMARY KEY NOT NULL,
	send_date TIMESTAMP NOT NULL,
	event  VARCHAR(500) NOT NULL
);