CREATE SCHEMA IF NOT EXISTS PRUEBAS_REMOTO;

DROP TABLE IF EXISTS PRUEBAS_REMOTO.USUARIOS;

DROP TABLE IF EXISTS PRUEBAS_REMOTO.MESSAGE_FALLBACK;

CREATE TABLE PRUEBAS_REMOTO.USUARIOS(
		identificador VARCHAR(36) PRIMARY KEY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		edad INTEGER NOT NULL
	);
CREATE TABLE PRUEBAS_REMOTO.MESSAGE_FALLBACK(
	id VARCHAR(36) PRIMARY KEY NOT NULL,
	send_date TIMESTAMP NOT NULL,
	event  VARCHAR(500) NOT NULL
);
