CREATE SCHEMA IF NOT EXISTS PRUEBAS;

DROP TABLE IF EXISTS PRUEBAS.USERS;

DROP TABLE IF EXISTS PRUEBAS.MESSAGE_FALLBACK;

CREATE TABLE PRUEBAS.USERS(
		identificador VARCHAR(36) PRIMARY KEY NOT NULL,
		nombre VARCHAR(100) NOT NULL,
		edad INTEGER NOT NULL
	);
	
CREATE TABLE PRUEBAS.MESSAGE_FALLBACK(
		id VARCHAR(36) PRIMARY KEY NOT NULL,
		send_date TIMESTAMP NOT NULL,
		event  VARCHAR(500) NOT NULL
	);